# 线性代数

## 向量

In [3]:
import torch
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

长度，维度

In [7]:
x.shape
#x.size()

torch.Size([4])

## 矩阵

In [8]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [10]:
#矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

## 张量算法的基本性质

In [14]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
A, B,A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法称为Hadamard积

In [12]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

张量乘以标量会让张量里的每个元素都和张量相乘

In [15]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

降维

In [16]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [17]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [19]:
#沿着0轴相加，沿着行
print(A)
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [23]:
#沿着1轴相加，沿着列，加之后只有一维，所以axis=1这个维度消失了
print(A)
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [24]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

非降维求和

In [29]:
print(A)
sum_A = A.sum(axis=1, keepdims=True)
#注意sum_A的size保持了5x1而不是变为了5
sum_A,sum_A.size()

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

例如，由于sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A+sum_A。

In [31]:
A + sum_A

tensor([[ 6.,  7.,  8.,  9.],
        [26., 27., 28., 29.],
        [46., 47., 48., 49.],
        [66., 67., 68., 69.],
        [86., 87., 88., 89.]])

In [33]:
#累计和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 点积（Dot product）

调用 **torch.dot(a,b)**

In [35]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [36]:
torch.sum(x * y)

tensor(6.)

**矩阵-向量积**


In [43]:
A.shape, x.shape, torch.mv(A, x),torch.mv(A, x).size()

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]),
 torch.Size([5]))

**矩阵-矩阵乘法**

In [44]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

---
## 范数

非正式地说，向量的范数是表示一个向量有多大。这里考虑的大小（size）概念不涉及维度，而是分量的大小。

$\displaystyle \|\mathbf{x}\|_{p}=\left(\sum_{i=1}^{n}\left|x_{i}\right|^{p}\right)^{1 / p}$

欧几里得距离是一个L2范数

In [55]:
import numpy as np
#L2
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

深度学习中更经常地使用L2范数的平方，也会经常遇到L1范数，它表示为向量元素的绝对值之和：

In [56]:
#L1
torch.abs(u).sum()

tensor(7.)

矩阵的Frobenius范数（Frobenius norm）是矩阵元素平方和的平方根，类似矩阵的L2范数

In [57]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

为什么用范数？

在深度学习中，我们经常试图解决优化问题：最大化分配给观测数据的概率; 最小化预测和真实观测之间的距离。用向量表示物品（如单词、产品或新闻文章），以便最小化相似项目之间的距离，最大化不同项目之间的距离。目标，或许是深度学习算法最重要的组成部分（除了数据），通常被表达为范数。


Test

In [81]:
#7
AA = torch.arange(24)
AA = AA.reshape(-1,3,4)
print(AA)
AA.sum(),AA.sum(axis = 0),AA.sum(axis = 1),AA.sum(axis = 1)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


(tensor(276),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]))

In [82]:
#6
A,A.sum(axis=1),A.sum(axis=1).size()
#A.sum(axis=1)降维了，不能进行广播运算

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

In [83]:
A,A.sum(axis=1,keepdims=True),A/A.sum(axis=1,keepdims=True)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]]))

In [88]:
#8
# 计算向量的L2范数
v = np.array([3, 4])
l2_norm = np.linalg.norm(v)
print("L2 Norm:", l2_norm)

#L1 范数：通过指定 ord=1 参数，可以计算 L1 范数。L1 范数是向量元素的绝对值之和。
l1_norm = np.linalg.norm(v,ord=1)
print("L1 Norm:", l1_norm)

# 计算矩阵的Frobenius范数（矩阵的L2范数）
A = np.array([[1, 2], [3, 4]])
frobenius_norm = np.linalg.norm(A)
print("Frobenius Norm:", frobenius_norm)

L2 Norm: 5.0
L1 Norm: 7.0
Frobenius Norm: 5.477225575051661
