In [41]:
import torch

## 入门

**理解什么是张量**


In [42]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过**shape**访问张量的形状（沿某个轴）

In [43]:
x.shape
#x.size() size是所有元素个数

torch.Size([12])

In [44]:
x.numel()

12

**reshape()** 来改变张量的形状

参数-1为自动计算，前提是你指定了另外所有的维度

In [45]:
x = x.reshape(3,4)
print(x)
x = x.reshape(-1,6)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


**zeros()/ones()** 来初始化全0或全1的张量

In [46]:
#注意，三维的第一个参数是通道数
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

**randn()** 用标准正态分布来初始化张量

In [47]:
torch.randn(2,3,4)

tensor([[[ 6.4120e-01, -1.1819e+00, -1.0057e+00,  2.6048e-01],
         [-9.6463e-01,  8.7672e-01, -7.3659e-01, -2.0357e-01],
         [ 8.4864e-01,  3.0938e-01,  6.7097e-01, -9.0740e-01]],

        [[ 7.1762e-01,  2.1004e+00,  1.3189e+00,  3.7963e-02],
         [ 1.5631e-03,  2.1249e-01, -1.7180e+00,  1.2655e+00],
         [-2.8296e-01,  9.6583e-01, -1.0381e+00,  7.5209e-01]]])

---

## 运算符

我们要在张量上执行数学运算

对于任意具有相同形状的张量，常见的标准算术运算\符（+、-、*、/和**）都可以被升级为按元素运算。



In [48]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [49]:
#包括求幂运算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

用cat()把两个张量连接起来，**dim=0/1**，0是沿行连接，1是沿列连接

In [50]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X,Y,torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

**==** 符号判断张量每个位置是否相等，**sum()** 求和，产生一个**单元素张量**

In [64]:
print(X == Y)
print(X > Y)
X.sum()

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


tensor(298.)

---

## 广播机制

broadcasting mechanism

这种机制的工作方式如
下：
1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对生成的数组执行按元素操作。


In [52]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

a,b矩阵形状不匹配，相加会将a复制列，b复制行，再相加

In [53]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [76]:
#三维的广播情况
A1 = torch.arange(12).reshape(-1,2,3)
A2 = torch.arange(0,6).reshape(-1,2,3)
print(A1)
print(A2)
A1+A2

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
tensor([[[0, 1, 2],
         [3, 4, 5]]])


tensor([[[ 0,  2,  4],
         [ 6,  8, 10]],

        [[ 6,  8, 10],
         [12, 14, 16]]])

---
## 索引和切片


和python类似，第一个元素索引是0，最后一个元素索引是-1

X[1:3]选中第二个和第三元素，注意X是二维的，所以是按行在取

“:”代表沿轴1（行）的所有元素

In [54]:
print(X)
X[-1],X[1:3],X[:,1]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([1., 5., 9.]))

In [55]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

---
## 节省内存

运行一些操作可能会导致为新结果分配内存。例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，
而是指向新分配的内存处的张量。

In [56]:
print(id(Y))
Y = Y + X
print(id(Y))

2545983843920
2545993117584


$Y[:]= <expression>$ 和$X += Y$ 都以用来节省内存开销

In [59]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))
before = id(X)
X += Y
id(X) == before

id(Z): 2545993174448
id(Z): 2545993174448


True

---
## 转换为其他对象

将深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。

In [63]:
print(type(X))
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

<class 'torch.Tensor'>


(numpy.ndarray, torch.Tensor)

用 **item()** 将单元素张量转换为python标量

In [61]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)